"""Report exporter: generates HTML and text reports of duplicate scan results."""

import os
from datetime import datetime

from .detector import DuplicateReport, DuplicateGroup


class ReportExporter:
    """Generates human-readable reports from duplicate detection results."""

    @staticmethod
    def export_html(report: DuplicateReport, output_path: str) -> str:
        """
        Generate a styled HTML report.

        Args:
            report: The duplicate detection report.
            output_path: Directory to write the report file to.

        Returns:
            Path to the generated HTML file.
        """
        filename = f"duplicate_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(output_path, filename)

        def format_size(size_bytes: int) -> str:
            if size_bytes < 1024:
                return f"{size_bytes} B"
            elif size_bytes < 1024 * 1024:
                return f"{size_bytes / 1024:.1f} KB"
            elif size_bytes < 1024 * 1024 * 1024:
                return f"{size_bytes / (1024 * 1024):.1f} MB"
            else:
                return f"{size_bytes / (1024 * 1024 * 1024):.2f} GB"

        def render_group(g: DuplicateGroup) -> str:
            rows = ""
            for img in g.images:
                rows += f"""
                <tr>
                    <td class="path">{img.path}</td>
                    <td>{format_size(img.file_size)}</td>
                </tr>"""
            return f"""
            <div class="group {g.duplicate_type}">
                <h3>📷 {g.duplicate_type.upper()} 重复 — {len(g.images)} 张图片
                    <span class="wasted">可释放: {format_size(g.total_wasted_size)}</span>
                </h3>
                <table>
                    <thead><tr><th>文件路径</th><th>大小</th></tr></thead>
                    <tbody>{rows}</tbody>
                </table>
            </div>"""

        groups_html = "\n".join(render_group(g) for g in report.all_groups)

        html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>重复图片扫描报告</title>
<style>
    body {{ font-family: -apple-system, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; color: #333; }}
    h1 {{ color: #1976D2; border-bottom: 3px solid #1976D2; padding-bottom: 10px; }}
    .summary {{ background: white; border-radius: 8px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
    .summary .stat {{ display: inline-block; margin-right: 30px; }}
    .stat .number {{ font-size: 24px; font-weight: bold; color: #1976D2; }}
    .stat .label {{ font-size: 12px; color: #666; }}
    .group {{ background: white; border-radius: 8px; padding: 15px; margin: 15px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
    .group.exact {{ border-left: 4px solid #4CAF50; }}
    .group.similar {{ border-left: 4px solid #FF9800; }}
    .group h3 {{ margin-top: 0; }}
    .wasted {{ color: #E53935; font-weight: normal; font-size: 14px; }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{ text-align: left; padding: 8px 12px; border-bottom: 1px solid #eee; }}
    th {{ color: #666; font-size: 12px; text-transform: uppercase; }}
    .path {{ font-family: monospace; font-size: 13px; word-break: break-all; }}
    .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 30px; }}
</style>
</head>
<body>
    <h1>🔍 重复图片扫描报告</h1>
    <div class="summary">
        <div class="stat"><span class="number">{report.total_images}</span><br><span class="label">扫描图片总数</span></div>
        <div class="stat"><span class="number">{report.total_duplicate_groups}</span><br><span class="label">重复组数</span></div>
        <div class="stat"><span class="number">{len(report.exact_groups)}</span><br><span class="label">精确重复组</span></div>
        <div class="stat"><span class="number">{len(report.similar_groups)}</span><br><span class="label">相似图片组</span></div>
        <div class="stat"><span class="number">{format_size(report.total_wasted_bytes)}</span><br><span class="label">可释放空间</span></div>
    </div>
    <p>扫描时间: {report.scan_time} | 扫描路径: {report.root_path}</p>
    {groups_html if groups_html else '<p>🎉 没有发现重复图片！</p>'}
    <div class="footer">Generated by Duplicate Image Finder</div>
</body>
</html>"""

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
        return filepath

    @staticmethod
    def export_text(report: DuplicateReport, output_path: str) -> str:
        """
        Generate a plain text report.

        Args:
            report: The duplicate detection report.
            output_path: Directory to write the report file to.

        Returns:
            Path to the generated text file.
        """
        filename = f"duplicate_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        filepath = os.path.join(output_path, filename)

        def format_size(size_bytes: int) -> str:
            if size_bytes < 1024 * 1024:
                return f"{size_bytes / 1024:.1f} KB"
            else:
                return f"{size_bytes / (1024 * 1024):.1f} MB"

        lines = []
        lines.append("=" * 60)
        lines.append("  重复图片扫描报告")
        lines.append("=" * 60)
        lines.append(f"扫描时间: {report.scan_time}")
        lines.append(f"扫描路径: {report.root_path}")
        lines.append(f"图片总数: {report.total_images}")
        lines.append(f"重复组数: {report.total_duplicate_groups}")
        lines.append(f"  - 精确重复: {len(report.exact_groups)} 组")
        lines.append(f"  - 相似图片: {len(report.similar_groups)} 组")
        lines.append(f"可释放空间: {format_size(report.total_wasted_bytes)}")
        lines.append("")

        for i, group in enumerate(report.all_groups, 1):
            lines.append(f"[组 {i}] {group.duplicate_type.upper()} - {len(group.images)} 张")
            lines.append(f"  可释放: {format_size(group.total_wasted_size)}")
            for img in group.images:
                lines.append(f"  - {img.path} ({format_size(img.file_size)})")
            lines.append("")

        lines.append("=" * 60)
        lines.append("Generated by Duplicate Image Finder")

        content = "\n".join(lines)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return filepath
